Exception occurred: Authentication credentials were not provided.
Traceback (most recent call last):
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 421, in initial
    self.check_permissions(request)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 339, in check_permissions
    self.permission_denied(
    ~~~~~~~~~~~~~~~~~~~~~~^
        request,
        ^^^^^^^^
        message=getattr(permission, 'message', None),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        code=getattr(permission, 'code', None)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 180, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.
Exception occurred: Authentication credentials were not provided.
Traceback (most recent call last):
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 421, in initial
    self.check_permissions(request)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 339, in check_permissions
    self.permission_denied(
    ~~~~~~~~~~~~~~~~~~~~~~^
        request,
        ^^^^^^^^
        message=getattr(permission, 'message', None),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        code=getattr(permission, 'code', None)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 180, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.
Exception occurred: Authentication credentials were not provided.
Traceback (most recent call last):
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 421, in initial
    self.check_permissions(request)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 339, in check_permissions
    self.permission_denied(
    ~~~~~~~~~~~~~~~~~~~~~~^
        request,
        ^^^^^^^^
        message=getattr(permission, 'message', None),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        code=getattr(permission, 'code', None)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 180, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.
Exception occurred: Authentication credentials were not provided.
Traceback (most recent call last):
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 421, in initial
    self.check_permissions(request)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 339, in check_permissions
    self.permission_denied(
    ~~~~~~~~~~~~~~~~~~~~~~^
        request,
        ^^^^^^^^
        message=getattr(permission, 'message', None),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        code=getattr(permission, 'code', None)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 180, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.
Exception occurred: Authentication credentials were not provided.
Traceback (most recent call last):
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 421, in initial
    self.check_permissions(request)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 339, in check_permissions
    self.permission_denied(
    ~~~~~~~~~~~~~~~~~~~~~~^
        request,
        ^^^^^^^^
        message=getattr(permission, 'message', None),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        code=getattr(permission, 'code', None)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 180, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.
Exception occurred: Authentication credentials were not provided.
Traceback (most recent call last):
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 421, in initial
    self.check_permissions(request)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 339, in check_permissions
    self.permission_denied(
    ~~~~~~~~~~~~~~~~~~~~~~^
        request,
        ^^^^^^^^
        message=getattr(permission, 'message', None),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        code=getattr(permission, 'code', None)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 180, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.
Exception occurred: Authentication credentials were not provided.
Traceback (most recent call last):
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 421, in initial
    self.check_permissions(request)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 339, in check_permissions
    self.permission_denied(
    ~~~~~~~~~~~~~~~~~~~~~~^
        request,
        ^^^^^^^^
        message=getattr(permission, 'message', None),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        code=getattr(permission, 'code', None)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 180, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.
Exception occurred: Authentication credentials were not provided.
Traceback (most recent call last):
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 421, in initial
    self.check_permissions(request)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 339, in check_permissions
    self.permission_denied(
    ~~~~~~~~~~~~~~~~~~~~~~^
        request,
        ^^^^^^^^
        message=getattr(permission, 'message', None),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        code=getattr(permission, 'code', None)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\BAKOONAHINDA\book_management_api\Book_Management\venv\Lib\site-packages\rest_framework\views.py", line 180, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.
